// authoringShapes.generated.ts — AUTO-GENERATED by nika-spec
// scripts/authoring-projector.py from stdlib/authoring-shapes-v0.1.yaml
// (the guided-edit shape registers SSOT: schema + armor). DO NOT EDIT —
// values change SPEC-FIRST. Regenerate: python3 scripts/authoring-projector.py --write
// Drift gate: --check (spec CI + consumer gates).

export interface SchemaShape {
  readonly id: string;
  /** The picker row (≤ 40 chars). */
  readonly label: string;
  /** The picker detail — teaches the why (≤ 120 chars). */
  readonly hint: string;
  /** The schema block, unindented (first line is `schema:`) — consumers re-indent. */
  readonly body: string;
}

export interface ArmorShape {
  readonly id: string;
  /** The task-level key the shape writes. */
  readonly key: 'retry' | 'on_error' | 'timeout';
  readonly label: string;
  readonly hint: string;
  /** The block, unindented (first line names the key) — consumers re-indent. */
  readonly body: string;
}

export const NIKA_SCHEMA_SHAPES: readonly SchemaShape[] = [
  {
    id: "fields",
    label: "named fields",
    hint: "The workhorse — an object whose required fields ARE the contract.",
    body: "schema:                # the response MUST match — structured output\n  type: object\n  required: [summary]   # SLOT: the fields you demand\n  properties:\n    summary: { type: string }\n",
  },
  {
    id: "list",
    label: "a list",
    hint: "items: an array field — extraction, findings, batch results.",
    body: "schema:\n  type: object\n  required: [items]\n  properties:\n    items:\n      type: array\n      items: { type: string }   # SLOT: the element shape\n",
  },
  {
    id: "verdict",
    label: "a verdict",
    hint: "boolean + reason — the judge shape gates and goldens consume.",
    body: "schema:\n  type: object\n  required: [verdict, reason]\n  properties:\n    verdict: { type: boolean }\n    reason: { type: string }\n",
  },
  {
    id: "grade",
    label: "a grade",
    hint: "enum: the closed set — the model cannot invent a fifth answer.",
    body: "schema:\n  type: object\n  required: [grade]\n  properties:\n    grade: { type: string, enum: [A, B, C] }   # SLOT: the closed set\n",
  },
] as const;

export const NIKA_ARMOR_SHAPES: readonly ArmorShape[] = [
  {
    id: "retry",
    key: "retry",
    label: "retry transient failures",
    hint: "rate limits · network — retries fire on transient errors only; exponential backoff + jitter are the defaults",
    body: "retry:\n  max_attempts: 3      # total tries · transient errors only\n  backoff_ms: 1000     # exponential + jitter by default\n",
  },
  {
    id: "recover",
    key: "on_error",
    label: "recover with a fallback",
    hint: "when it still fails, substitute a value — downstream sees success, shape-stable",
    body: "on_error:\n  recover: \"\"   # SLOT: a literal — or ${{ tasks.<id>.output }}\n",
  },
  {
    id: "skip",
    key: "on_error",
    label: "skip on error",
    hint: "let the DAG continue — status: skipped, the original error stays readable at tasks.<id>.error",
    body: "on_error:\n  skip: true   # downstream sees skipped · the error stays readable\n",
  },
  {
    id: "timeout",
    key: "timeout",
    label: "bound its time",
    hint: "a Go duration (30s · 5m) — the task fails NIKA-TIMEOUT instead of hanging the run",
    body: "timeout: \"60s\"   # SLOT: Go duration — 30s · 5m · 1h\n",
  },
] as const;
