// cursorRules.ts — the `.cursor/rules/nika.mdc` teaching text (pure · no vscode).
//
// The extension writes this file into a user's workspace so an AI
// assistant learns the language before it writes a workflow. It is the
// highest-leverage teaching surface the extension owns: every rule here
// is repeated by every model that reads it, in every file it writes.
// So it teaches exactly what the engine it ships with accepts (nika
// 0.109 · the nine-key envelope) — and it SAYS which engine it teaches,
// so a stale copy can be recognised and refreshed (`shouldRewriteRules`).
//
// Vocabulary that derives from the binary (providers) is injected by the
// caller at generation time; a hardcoded list here would be exactly the
// teaching-drift class the own-corpus law exists for.

/** Provider groups for the generated rules (derived from the canon). */
export interface RulesIntel {
  cloud: string[];
  local: string[];
  test: string[];
}

/** The engine language this text teaches — bump WITH the language. */
export const RULES_TEACHES = 'nika 0.109';

/** The generation stamp: a file carrying it is current; a file carrying
 *  the header but not this exact line was generated by an older
 *  extension and is rewritten. */
export const RULES_STAMP = `Generated by the Nika extension · teaches ${RULES_TEACHES} · the nine-key envelope · rewritten when this line goes stale`;

const HEADER = '# Nika Workflow Language';

/** True when `existing` is OUR generated file at an older language —
 *  never a user's own rules (no header) and never a current one. */
export function shouldRewriteRules(existing: string): boolean {
  return existing.includes(HEADER) && !existing.includes(RULES_STAMP);
}

export function buildCursorRules(providers?: RulesIntel): string {
  const providerLines = providers
    ? [
        '## Providers (from the embedded canon at setup time)',
        `cloud: ${providers.cloud.join(', ')}`,
        `local (sovereign · zero-cloud): ${providers.local.join(', ')}`,
        `test: ${providers.test.join(', ')}`,
      ]
    : [
        '## Providers',
        'Run `nika spec --canon` for the canonical provider list (cloud · local-sovereign · test).',
      ];

  return [
    '---',
    'description: Nika workflow language rules for AI assistance',
    'globs: ["**/*.nika.yaml", "**/*.nika.yml"]',
    'alwaysApply: false',
    '---',
    '',
    HEADER,
    '',
    RULES_STAMP,
    '',
    '## The envelope · exactly nine top-level keys',
    '`nika` · `model` · `inputs` · `const` · `secrets` · `permits` · `run` · `tasks` · `outputs`. Nothing else at the top level.',
    '- `nika: <kebab-id>` is the IDENTITY line: the workflow\'s own name (`nika: release-notes`). Never `nika: v1` and never a `workflow:` block (both died with the nine-key envelope · NIKA-PARSE-005). A description is a `#` comment ABOVE `nika:`.',
    '- Extension: `.nika.yaml`. After the identity line: `model:` (the default `provider/name`), the value authorities, `permits:`, then `tasks:` (a MAP · the key IS the task id · never a `- id:` list).',
    '',
    '## 4 Verbs (locked forever)',
    '- infer: LLM call ({ prompt, system?, temperature?, schema? })',
    '- exec: subprocess ({ command: ["prog", "arg"] argv-only, cwd?, shell? for pipes/redirects, capture: stdout|stderr|combined|structured })',
    '- invoke: builtin/MCP tool ({ tool, args }) — HTTP fetch = `tool: nika:fetch` (a TOOL, not a verb)',
    '- agent: agent loop ({ model, prompt, tools: default-deny whitelist, max_turns, max_tokens_total })',
    '',
    '## Key Rules',
    '- Interpolation · 5 namespaces. The THREE value authorities: ${{ inputs.x }} (typed, caller-supplied · a deployment-supplied value is an inputs: entry with required: false and a default:) · ${{ const.x }} (fixed value baked into the file) · ${{ secrets.x }} (vault-backed, masked). Plus the two runtime ones: ${{ with.alias }} · ${{ tasks.id.output }}',
    '- DEAD: `config:`, `vars:` and `env:` are NOT envelope fields and ${{ config.X }} / ${{ vars.X }} / ${{ env.X }} are NOT namespaces (NIKA-PARSE-005 · NIKA-VALUES-001/002/003). Classify each value into the authority its ROLE commands — a typed parameter is inputs:, a fixed value const:, a governed store reference secrets:. Never a blind rename',
    '- `tasks.*` ONLY inside with:/after:/on_error.recover/outputs (NIKA-VAR-021 elsewhere — hoist it into with:)',
    '- The binding IS the edge: with: { alias: "${{ tasks.id.output }}" } (quote it in flow style — or use block style) then the body reads ${{ with.alias }}',
    '- Order without data: after: { task_id: success } (predicates: success | failure | skipped | terminal | unwind) — depends_on is dead (NIKA-PARSE-024 · check --fix migrates)',
    '- Cleanup is a TASK on an unwind edge: `after: { producer: unwind }` runs once the producer has started and settles (success · failure · timeout · cancel), never scheduled in a wave. `on_finally:` is dead (NIKA-PARSE-005)',
    '- on_error is a mapping with exactly one action: `on_error: { skip: true }` or `on_error: { recover: <value> }`. Failure is the default — there is no fail_workflow',
    '- Model: combined form `model: provider/name` (e.g. ollama/llama3.2 · mock/echo for tests)',
    '- timeout is a Go-duration string, quoted: timeout: "5m"',
    '- Secrets: declare `secrets: { name: { source: env|vault|file, key: … } }` and read ${{ secrets.name }} — masked in logs/traces. NEVER literal keys in YAML, and never a bare env read',
    '- inputs: entries are TYPED declarations (`type:` required · `required: true` for a caller-supplied value · `required: false` + `default:` for a deployment value). Types are the closed grammar: null · bool · integer · number · string · bytes · uri · path · duration · timestamp, plus constructors { array: T } · { map: T } · { object: {…} } · { union: […] } · { enum: […] }. `boolean` and bare `array`/`object` are NOT types',
    '- extract: named jq bindings on a task (the old `output:` block is dead) · outputs: = the workflow return value',
    '- when: CEL conditional, LOCAL reads only (the value authorities · with · item/index) · retry: { max_attempts, backoff } · for_each is a BLOCK { items: "${{ … }}", max_parallel?: N, fail_fast?: false } · lift: is the one door that opens a named law (taint · data-as-code · a because: always) — declassify:, inert: and to: trusted are dead',
    '- Effects need a boundary: `permits:` (fs · net · exec · tools) — no `policy:` block, no `types:` block, no `assert:` block (all dead · a shape rides the verb\'s own `schema:` or a task\'s `returns:` · obligations are proven on the trace with `nika trace verify`)',
    '- After writing or editing any *.nika.yaml, ALWAYS run `nika check <file> --json` and fix every finding before finishing. Never declare the task done while findings remain. Unknown code → `nika explain NIKA-XXXX`.',
    '',
    ...providerLines,
    '',
    'Refer to AGENTS.md for complete documentation · `nika spec <section>` for the embedded spec.',
  ].join('\n');
}
