// verbStarters.generated.ts — AUTO-GENERATED by nika-spec
// scripts/starters-projector.py from stdlib/verb-starters-v0.1.yaml
// (the per-verb task-body starters SSOT). DO NOT EDIT — values change
// SPEC-FIRST. Regenerate: python3 scripts/starters-projector.py --write
// Drift gate: --check (spec CI + consumer gates).

export interface VerbStarter {
  readonly id: string;
  /** The picker row (≤ 40 chars). */
  readonly label: string;
  /** The picker detail — teaches the why (≤ 120 chars). */
  readonly hint: string;
  /** The verb block, unindented (first line is `<verb>:`) — consumers re-indent. */
  readonly body: string;
}

export type NikaVerb = 'infer' | 'exec' | 'invoke' | 'agent';

export const NIKA_VERB_STARTERS: Record<NikaVerb, readonly VerbStarter[]> = {
  infer: [
    {
      id: "infer-prompt",
      label: "prompt → text",
      hint: "The minimal LLM call — the task's output is the model's response.",
      body: "infer:\n  prompt: \"Say hello in French\"   # SLOT: the one model job\n",
    },
    {
      id: "infer-typed",
      label: "prompt → typed JSON",
      hint: "schema: validates the response — type-safe extraction, no prose parsing.",
      body: "infer:\n  prompt: \"Extract the key facts from: ${{ vars.input }}\"   # SLOT: what to extract\n  schema:                # the response MUST match — structured output\n    type: object\n    required: [summary]\n    properties:\n      summary: { type: string }\n",
    },
    {
      id: "infer-tuned",
      label: "system + model + tuning",
      hint: "A voice, a model override (<provider>/<name> · local-first) and sampling bounds.",
      body: "infer:\n  system: \"You are a senior software architect.\"   # SLOT: the voice\n  prompt: \"Research the topic: ${{ vars.topic }}\"  # SLOT: the job\n  model: ollama/qwen3.5:4b   # SLOT: override · local runs unpriced, never free\n  temperature: 0.3\n  max_tokens: 2000\n",
    },
  ],
  exec: [
    {
      id: "exec-shell",
      label: "shell command",
      hint: "String form runs via the OS shell — pipes and redirects work.",
      body: "exec:\n  command: \"cargo test --workspace --lib\"   # SLOT: the command\n",
    },
    {
      id: "exec-argv",
      label: "argv · no shell",
      hint: "Array form is direct execve — the one obvious way to carry interpolated or untrusted values.",
      body: "exec:\n  command: [\"echo\", \"${{ vars.message }}\"]   # SLOT: program + args · each element substituted independently\n",
    },
    {
      id: "exec-captured",
      label: "capture structured",
      hint: "cwd + structured capture — stdout, stderr and the exit code become fields.",
      body: "exec:\n  command: \"git status --short\"   # SLOT: the command\n  cwd: \".\"                        # SLOT: working directory\n  capture: structured\n",
    },
  ],
  invoke: [
    {
      id: "invoke-builtin",
      label: "builtin tool",
      hint: "nika:<tool> — pick from the embedded catalog; args are tool-specific.",
      body: "invoke:\n  tool: \"nika:read\"       # SLOT: pick from the catalog\n  args:\n    path: \"./README.md\"   # SLOT: args are tool-specific\n",
    },
    {
      id: "invoke-mcp",
      label: "MCP tool",
      hint: "mcp:<server>/<tool> — the server comes from the engine's MCP registry.",
      body: "invoke:\n  tool: \"mcp:browser/navigate\"   # SLOT: mcp:<server>/<tool>\n  args:\n    url: \"https://example.com\"   # SLOT\n",
    },
  ],
  agent: [
    {
      id: "agent-tools",
      label: "agent + tools",
      hint: "The multi-turn loop — tools are default-deny, grant the least set explicitly.",
      body: "agent:\n  system: \"You are a research assistant.\"           # SLOT: the voice\n  prompt: \"Research the topic: ${{ vars.topic }}\"   # SLOT: the mission\n  tools: [\"nika:fetch\"]   # SLOT: default-deny · least privilege\n  max_turns: 10\n",
    },
    {
      id: "agent-typed",
      label: "agent → typed final",
      hint: "schema: validates the FINAL message — name the contract in the prompt so the loop lands on it.",
      body: "agent:\n  system: \"You are a meticulous analyst.\"\n  prompt: \"Produce findings for: ${{ vars.topic }}\"   # SLOT: the mission · name the contract + done condition\n  tools: [\"nika:fetch\", \"nika:read\"]   # SLOT: least privilege\n  max_turns: 12\n  schema:                # the final message MUST match\n    type: object\n    required: [findings]\n    properties:\n      findings: { type: array, items: { type: string } }\n",
    },
  ],
} as const;
