// sync-icons.mjs — vendor the SuperNovae icon ontology into the extension.
//
// The nika icon library lives with the site (design/icons.yaml → build.mjs
// → public/brand/icons/*.svg · grid 24 · stroke 2 · currentColor). The
// extension CHECKS IN the picked subset as src/icons.generated.ts (the
// design-tokens.generated.ts pattern: regenerated locally when the
// ontology changes, committed, never fetched at build time).
//
//   node scripts/sync-icons.mjs            # regenerate from ../../website
//   NIKA_SITE=/path node scripts/sync-icons.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const site = process.env.NIKA_SITE ?? resolve(here, '../../../website');
const iconsDir = resolve(site, 'public/brand/icons');

// entity id → baked file stem. The picked subset: the welcome capability
// grid + the chrome doors that have a domain icon.
const PICK = {
  'feature/check': 'feature-check',
  'feature/preflight': 'feature-preflight',
  'feature/history': 'feature-history',
  'feature/report': 'feature-report',
  'builtin/inspect': 'builtin-inspect',
  'feature/permits': 'feature-permits',
  'feature/explain': 'feature-explain',
  'ui/book': 'ui-book',
  'feature/generate': 'feature-generate',
  'feature/mcp': 'feature-mcp',
  'feature/examples': 'feature-examples',
  'feature/replay': 'feature-replay',
};

if (!existsSync(iconsDir)) {
  console.error(`sync-icons: site icons not found at ${iconsDir} — set NIKA_SITE`);
  process.exit(1);
}

const entries = [];
for (const [id, stem] of Object.entries(PICK)) {
  const p = resolve(iconsDir, `${stem}.svg`);
  let svg = readFileSync(p, 'utf8')
    .replace(/<!--[\s\S]*?-->\s*/g, '')
    .replace(/\s+data-nika="[^"]*"/, '')
    .trim();
  if (!svg.includes('aria-hidden')) {
    svg = svg.replace('<svg ', '<svg aria-hidden="true" ');
  }
  entries.push(`  '${id}': '${svg.replace(/'/g, "\\'")}',`);
}

const out = `// icons.generated.ts — the SuperNovae icon ontology, vendored.
// GENERATED by scripts/sync-icons.mjs from the site's baked library
// (public/brand/icons · grid 24 · stroke 2 · currentColor). Do not edit
// by hand — rerun the script when the ontology changes upstream.
/* eslint-disable */
export const ONTOLOGY_ICON = {
${entries.join('\n')}
} as const;
export type OntologyIconId = keyof typeof ONTOLOGY_ICON;
`;
writeFileSync(resolve(here, '../src/icons.generated.ts'), out);
console.log(`sync-icons: ${entries.length} entities vendored → src/icons.generated.ts`);
